nextest-version = "0.9.5"
experimental = []

[profile.default]
default-filter = "all()"
test-threads = "num-cpus"
status-level = "pass"
fail-fast = false
retries = 0
test-timeout = "300s"
slow-time = "30s"
failures-output = "immediate-final"
success-output = "never"

[profile.ci]
inherit = "default"
status-level = "all"
test-timeout = "300s"
slow-time = "60s"
retries = 0
